// ============================================================================
// BACKUP LOGIC - Export/Import Project Data
// ============================================================================

import JSZip from 'jszip';
import { format } from 'date-fns';
import type {
  Project,
  Milestone,
  Task,
  ActivityEvent,
  Note,
  Snippet,
  DocumentMeta,
  EmbeddedFile,
  WeeklyReport,
  Decision,
  ProjectUpdate,
} from './types';
import { db } from '../storage/db';

export interface BackupData {
  version: string;
  exportedAt: string;
  project: Project;
  milestones: Milestone[];
  tasks: Task[];
  activityEvents: ActivityEvent[];
  notes: Note[];
  snippets: Snippet[];
  documentMetas: DocumentMeta[];
  embeddedFiles: EmbeddedFile[];
  weeklyReports: WeeklyReport[];
  decisions: Decision[];
  projectUpdates: ProjectUpdate[];
}

/**
 * Export a project and all its data to a ZIP file
 */
export async function exportProject(projectId: string): Promise<Blob> {
  // Gather all project data
  const project = await db.projects.get(projectId);
  if (!project) {
    throw new Error('Project not found');
  }

  const [
    milestones,
    tasks,
    activityEvents,
    notes,
    snippets,
    documentMetas,
    weeklyReports,
    decisions,
    projectUpdates,
  ] = await Promise.all([
    db.milestones.where('projectId').equals(projectId).toArray(),
    db.tasks.where('projectId').equals(projectId).toArray(),
    db.activityEvents.where('projectId').equals(projectId).toArray(),
    db.notes.where('projectId').equals(projectId).toArray(),
    db.snippets.where('projectId').equals(projectId).toArray(),
    db.documentMetas.where('projectId').equals(projectId).toArray(),
    db.weeklyReports.where('projectId').equals(projectId).toArray(),
    db.decisions.where('projectId').equals(projectId).toArray(),
    db.projectUpdates.where('projectId').equals(projectId).toArray(),
  ]);

  // Get embedded files
  const embeddedKeys = documentMetas
    .filter((d) => d.storageMode === 'EMBEDDED' && d.embeddedKey)
    .map((d) => d.embeddedKey!);

  const embeddedFiles = await db.embeddedFiles.bulkGet(embeddedKeys);
  const validEmbeddedFiles = embeddedFiles.filter((f): f is EmbeddedFile => f !== undefined);

  // Create backup data
  const backupData: BackupData = {
    version: '1.0',
    exportedAt: new Date().toISOString(),
    project,
    milestones,
    tasks,
    activityEvents,
    notes,
    snippets,
    documentMetas,
    embeddedFiles: validEmbeddedFiles,
    weeklyReports,
    decisions,
    projectUpdates,
  };

  // Create ZIP
  const zip = new JSZip();

  // Add index.json with all metadata
  const index = {
    ...backupData,
    embeddedFiles: backupData.embeddedFiles.map((f) => ({
      ...f,
      blob: undefined, // Will be stored separately
    })),
  };
  zip.file('index.json', JSON.stringify(index, null, 2));

  // Add embedded files as separate binary files
  for (const embeddedFile of validEmbeddedFiles) {
    if (embeddedFile.blob) {
      zip.file(`files/${embeddedFile.key}`, embeddedFile.blob);
    }
  }

  // Add README
  const readme = `# Dev Organizer Backup

Project: ${project.name}
Exported: ${format(new Date(), 'yyyy-MM-dd HH:mm:ss')}

## Contents

- index.json: Project metadata and structure
- files/: Embedded files (if any)

## Import

To import this backup:
1. Open Dev Organizer
2. Go to a project's Docs & Reports page
3. Click "Import Backup"
4. Select this ZIP file

---

Generated by Dev Organizer v1.0
`;
  zip.file('README.txt', readme);

  // Generate ZIP blob
  return await zip.generateAsync({ type: 'blob' });
}

/**
 * Import a project from a ZIP backup file
 */
export async function importProject(zipBlob: Blob): Promise<string> {
  const zip = await JSZip.loadAsync(zipBlob);

  // Read index.json
  const indexFile = zip.file('index.json');
  if (!indexFile) {
    throw new Error('Invalid backup: index.json not found');
  }

  const indexContent = await indexFile.async('text');
  const backupData: BackupData = JSON.parse(indexContent);

  // Validate version
  if (backupData.version !== '1.0') {
    throw new Error(`Unsupported backup version: ${backupData.version}`);
  }

  // Check if project already exists
  const existingProject = await db.projects.get(backupData.project.id);
  if (existingProject) {
    throw new Error(`Project "${backupData.project.name}" already exists. Please delete it first or rename.`);
  }

  // Import project data
  await db.transaction('rw', [
    db.projects,
    db.milestones,
    db.tasks,
    db.activityEvents,
    db.notes,
    db.snippets,
    db.documentMetas,
    db.embeddedFiles,
    db.weeklyReports,
    db.decisions,
    db.projectUpdates,
  ], async () => {
    // Import project
    await db.projects.add(backupData.project);

    // Import milestones
    if (backupData.milestones.length > 0) {
      await db.milestones.bulkAdd(backupData.milestones);
    }

    // Import tasks
    if (backupData.tasks.length > 0) {
      await db.tasks.bulkAdd(backupData.tasks);
    }

    // Import activity events
    if (backupData.activityEvents.length > 0) {
      await db.activityEvents.bulkAdd(backupData.activityEvents);
    }

    // Import notes
    if (backupData.notes.length > 0) {
      await db.notes.bulkAdd(backupData.notes);
    }

    // Import snippets
    if (backupData.snippets.length > 0) {
      await db.snippets.bulkAdd(backupData.snippets);
    }

    // Import document metas
    if (backupData.documentMetas.length > 0) {
      await db.documentMetas.bulkAdd(backupData.documentMetas);
    }

    // Import embedded files
    for (const embeddedFileMeta of backupData.embeddedFiles) {
      const fileInZip = zip.file(`files/${embeddedFileMeta.key}`);
      if (fileInZip) {
        const blob = await fileInZip.async('blob');
        await db.embeddedFiles.add({
          ...embeddedFileMeta,
          blob,
        });
      }
    }

    // Import weekly reports
    if (backupData.weeklyReports.length > 0) {
      await db.weeklyReports.bulkAdd(backupData.weeklyReports);
    }

    // Import decisions
    if (backupData.decisions.length > 0) {
      await db.decisions.bulkAdd(backupData.decisions);
    }

    // Import project updates
    if (backupData.projectUpdates.length > 0) {
      await db.projectUpdates.bulkAdd(backupData.projectUpdates);
    }
  });

  return backupData.project.id;
}

/**
 * Export all data (all projects) to a ZIP file
 */
export async function exportAllData(): Promise<Blob> {
  // Get all data
  const [
    projects,
    milestones,
    tasks,
    activityEvents,
    notes,
    snippets,
    documentMetas,
    embeddedFiles,
    weeklyReports,
    decisions,
    projectUpdates,
    settings,
  ] = await Promise.all([
    db.projects.toArray(),
    db.milestones.toArray(),
    db.tasks.toArray(),
    db.activityEvents.toArray(),
    db.notes.toArray(),
    db.snippets.toArray(),
    db.documentMetas.toArray(),
    db.embeddedFiles.toArray(),
    db.weeklyReports.toArray(),
    db.decisions.toArray(),
    db.projectUpdates.toArray(),
    db.settings.toArray(),
  ]);

  const fullBackup = {
    version: '1.0',
    exportedAt: new Date().toISOString(),
    projects,
    milestones,
    tasks,
    activityEvents,
    notes,
    snippets,
    documentMetas,
    embeddedFiles: embeddedFiles.map((f) => ({
      ...f,
      blob: undefined, // Will be stored separately
    })),
    weeklyReports,
    decisions,
    projectUpdates,
    settings,
  };

  // Create ZIP
  const zip = new JSZip();

  // Add index.json
  zip.file('index.json', JSON.stringify(fullBackup, null, 2));

  // Add embedded files
  for (const embeddedFile of embeddedFiles) {
    if (embeddedFile.blob) {
      zip.file(`files/${embeddedFile.key}`, embeddedFile.blob);
    }
  }

  // Add README
  const readme = `# Dev Organizer Full Backup

Exported: ${format(new Date(), 'yyyy-MM-dd HH:mm:ss')}
Projects: ${projects.length}

## Contents

This is a complete backup of all your Dev Organizer data including:
- All projects
- All milestones, tasks, and activity
- All notes and snippets
- All documents and files
- All reports and settings

## Import

To restore this backup:
1. Open Dev Organizer
2. Go to Settings or Dashboard
3. Click "Import Full Backup"
4. Select this ZIP file

⚠️ WARNING: Importing will merge with existing data. Duplicate IDs will cause errors.

---

Generated by Dev Organizer v1.0
`;
  zip.file('README.txt', readme);

  return await zip.generateAsync({ type: 'blob' });
}

/**
 * Get backup filename
 */
export function getBackupFilename(projectName?: string): string {
  const timestamp = format(new Date(), 'yyyy-MM-dd-HHmm');
  if (projectName) {
    const safeName = projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    return `dev-organizer-${safeName}-${timestamp}.zip`;
  }
  return `dev-organizer-full-backup-${timestamp}.zip`;
}
